use_frameworks!

platform :ios, '9.0'

target 'IdentityCardDetector_Example' do
  pod 'IdentityCardDetector', :path => '../'

  target 'IdentityCardDetector_Tests' do
    inherit! :search_paths

    
  end
end
